# Smarthome stack - Kris 22
# 
# Create networks before running docker-compose -p smarthome up -d
# docker network create inside_network

# .env file variables:
# $PUID
# $PGID
# $TZ i.e. "Europe/London" 
# $DOCKERDIR location of docker and configuration files
# $SESSIONSECRET for zwave2mqtt

# Stack applications:
# [9000]  HomeAssistant
# [9001]  HomeBridge
# [9002]  Mosquitto MQTT
# [9003]  ESPHome
# [9004]  CodeServer
#
# Additional applications:
# [9005]  zwave2mqtt
# [9006]  zigbee2mqtt
#
# Core applications:
# [10000] Portainer agent

version: "3.7"

networks:
  inside_network:
    external:
      name: inside_network

services:

### Core applications
### Applications required outside of the stack
  
  # Portainer: Portainer agent for remote management
  #
  portainer_agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: always
    ports:
      - "10000:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - inside_network  
  
### Smarthome stack
### Applications for managing smarthome and IOT devices

  # HomeAssistant: IOT platform
  #
  # After installation
  # sudo chown -R <user> app_data/homeassistant
  # nano app_data/homeassistant/configuration.yaml
  # 
  # Add the following to change the HomeAssistant port to 9001
  # http:
  #   server_port: 9000
  #
  # restart the container: sudo docker container restart homeassistant
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/app_data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro

  # HomeBridge: IOT platform
  #
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=9001 # set the HomeBridge port
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/app_data/homebridge:/homebridge
      - /etc/localtime:/etc/localtime:ro

  # Mosquitto: MQTT broker
  #
  # set MQTT username and password
  # 
  # sudo docker exec -it mosquitto sh
  # mosquitto_passwd - c mosquitto/config/mqtt_passwd mqtt
  #
  # set a password and exit the environment
  # exit

  # create mosquitto.conf
  # sudo nano app_data/mosquitto/config/mosqitto.conf 
  # 
  # listener 1883
  # allow_anonymous false
  # password_file /mosquitto/config/mqtt_passwd
  # persistence true
  # persistence_location /mosquitto/data/
  # log_dest file /mosquitto/log/mosquitto.log
  #
  # sudo docker container restart mosquitto
  #
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - '9002:1883'
    restart: unless-stopped  
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - ${DOCKERDIR}/app_data/mosquitto/config:/mosquitto/config/
      - ${DOCKERDIR}/app_data/mosquitto/data:/mosquitto/data/
      - ${DOCKERDIR}/app_data/mosquitto/log:/mosquitto/log/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - inside_network 

  # ESPHome: IOT development platform for ESP8266 and ESP32 modules
  #
  esphome:
    image: esphome/esphome:dev
    container_name: esphome
    restart: always
    privileged: true
    ports: 
      - "9003:6052"
      - "6123:6123"
    environment:
      - HOME="/"
    volumes:
      - ${DOCKERDIR}/app_data/esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    command: config/ dashboard
    networks:
      - inside_network

  # Code-Server: IDE platform for HomeAssisant
  #
  # The following extensions should be enabled for auto complete etc:
  # 
  # emilast.LogFileHighlighter
  # keesschollaart.vscode-home-assistant
  # oderwat.indent-rainbow
  # redhat.vscode-yaml
  # usernamehw.errorlens
  #
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    restart: always
    ports:
      - "9004:8443"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ${DOCKERDIR}/app_data/code-server:/config
      - ${DOCKERDIR}/app_data/homeassistant:/config/workspace
      - /etc/localtime:/etc/localtime:ro
    networks:
      - inside_network

### Additional applications
### zwave2mqtt and zigbee2mqtt configuration

  # ZWave2MQTT: IOT platform
  # MQTT URL: mtqq://mosquitto:1883
  #
  #zwavejs2mqtt:
  #  image: zwavejs/zwavejs2mqtt:latest
  #  container_name: zwavejs2mqtt
  #  restart: always
  #  tty: true
  #  stop_signal: SIGINT
  #  ports:
  #    - "9005:8091" # management interface
  #    - "3000:3000" # ZWave JS websocket server
  #  environment:
  #    - PGID=${PGID}
  #    - PUID=${PUID}
  #    - SESSION_SECRET=${SESSION_SECRET}
  #    - ZWAVJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
  #    - TZ=${TZ}
    #devices:
    #  Use the /dev/serial/by-id/X serial device for your ZWave device
    #  - '/dev/serial/by-id/insert_stick_reference_here:/dev/zwave'
  #  volumes:
  #    - ${DOCKERDIR}/app_data/zwavejs2mqtt:/usr/src/app/store
  #    - /etc/localtime:/etc/localtime:ro
  #  networks: 
  #    - inside_network
  
  # Zigbee2MQTT: IOT platform
  # MQTT URL: mqtt://mosquitto:1883
  #
  #zigbee2mqtt:
  #  image: koenkk/zigbee2mqtt
  #  container_name: zigbee2mqtt
  #  restart: always
  #  ports:
  #    - 9006:8080
  #  environment:
  #    - PGID=${PGID}
  #    - PUID=${PUID}
  #    - TZ=${TZ}
    #devices:
    #  Use the /dev/serial/by-d/X serial device for your Zigbee device
    #  - '/dev/serial/by-id/insert_stick_reference_here:/dev/zigbee'
  #  volumes:
  #    - ${DOCKERDIR}/app_data/zigbee2mqtt:/app/data
  #    - /etc/localtime:/etc/localtime:ro
  #  networks:
  #    - inside_network